### PR TITLE
add musl release target

### PR DESCRIPTION
**Pull request by gustofarbi**
this PR adds a musl release to the list of current releases

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Why?

**Comment by gustofarbi** [comment]
shouldve added a better description 😅 , we are using resvg inside an alpine container in two apps and it is pretty time consuming to have an extra layer to build resvg, would be nice to just download the prebuilt binary

**Comment by RazrFalcon** [comment]
Sorry, but this is a very niche use case. You should host prebuilt versions yourself.

**Comment by RazrFalcon** [comment]
Because you can easily build it yourself.

**Pull request closed without merging**
