### PR TITLE
Added usvg_converter binary

### PR DESCRIPTION
**Pull request by Vrroom**
Hello!

Thanks a lot for your project. I haven't found anything like it! I am working on a project that uses vector graphics heavily. The project uses a mix of javascript and python. My code failed for certain graphics (such as those which used mixed coordinates or had metadata). I needed an SVG simplifier such as usvg. I couldn't find an equivalent in python/javascript that worked. Even inkscape's plain svg option wasn't satisfactory. 

The only thing that worked eventually was your library. While you provide a dump svg option, it needs some digging, especially for people unfamiliar with Rust (such as myself). As a consequence I think my tiny contribution will be useful to others. 

Thanks for all your wonderful work!!

### CODE REVIEW

**Comment by RazrFalcon** [comment]
How is it different from `cd usvg && cargo run`?

**Comment by Vrroom** [comment]
Really sorry. I didn't notice that the first time round. My bad.

**Comment by RazrFalcon** [comment]
No worries. There are prebuilt binaries of the `usvg` on the Releases page too.

**Comment by Vrroom** [comment]
Oh that is great! 

I'll briefly give you a sense of my project and how your project has immensely simplified life for me. 

You know how SVGs have `<g>` tags that artists can use to organize stuff. That is often missing. I think that this is a perceptual grouping problem and I'm making a data-driven algorithm that automatically groups paths or groups of paths. 

I made an annotation interface to obtain grouping data and scraped the web for graphics to be annotated. Unfortunately, due to the complexities of the SVG standard, my annotation interface kept failing. Now having integrated `usvg` into my preprocessing pipeline, I don't have to worry about those complexities anymore!

**Comment by RazrFalcon** [comment]
Glad to hear that you found it useful!

**Pull request closed without merging**
