### PR TITLE
Add support for no `width` and no `height` on images

### PR DESCRIPTION
**Pull request by LaurenzV**

### CODE REVIEW

**Comment by LaurenzV** [comment]
Closes #714

**Comment by LaurenzV** [comment]
The images are linked by relative paths because that's how it was before and I didn't know if I should change it. Should I embed them as base64 strings instead?

**Comment by RazrFalcon** [comment]
References are fine.

As for the code, I would suggest using `tiny_skia_path::Size::scale_to_width` and `scale_to_height`. They are basically the same, but might make the code nicer. The current implementation is too verbose. 
I would also suggest calling `convert_user_length` first and then matching `Option<T>` pair.

**Comment by LaurenzV** [comment]
> As for the code, I would suggest using tiny_skia_path::Size::scale_to_width and scale_to_height.

Seems like this API is only available for `IntSize` and not `Size`?

**Comment by RazrFalcon** [comment]
Much better now.

>Seems like this API is only available for IntSize and not Size?

Weird, ok.

Also about the PR name. We do support optional width/height. We do not support aspect preserving. 
So I guess it should be called: "Preserve image aspect ratio when `width` or `height` are missing.". Does this sound ok?

**Comment by RazrFalcon** [comment]
Also, I think we need tests with non-rectangular images. Otherwise the aspect is always 1:1 and we're not testing anything. No?

**Comment by RazrFalcon** [comment]
I guess current tests are fine, because you do scale the image, but the aspect is always 1:1 right now. So I guess a single test with a non-rectangular image would be nice.

Let's use this image:

image32x16

**Comment by LaurenzV** [comment]
> Also, I think we need tests with non-rectangular images. Otherwise the aspect is always 1:1 and we're not testing anything. No?

It's not necessarily about the aspect.

Before: If we have an image with size 100x100, but set only the height to 200, then the image would be assumed to be 100x200 -> It will get shifted instead.

Now:  If we have an image with size 100x100, but set only the height to 200, then the width will be increased by the same ratio that the height would increase/decrease, so in this case 200 -> the result is 200x200.

**Comment by LaurenzV** [comment]
> I guess current tests are fine, because you do scale the image, but the aspect is always 1:1 right now. So I guess a single test with a non-rectangular image would be nice.

Okay, will add it.

**Comment by RazrFalcon** [comment]
Thanks!

**Pull request merged**
