### PR TITLE
Add error case: 'the previous segment must be M/L/C'

### PR DESCRIPTION
**Pull request by yisibl**
This PR adds a test case to ensure that special path parsing does not throw an error. The following error can be reproduced in the <=0.28.0 version.

```
git checkout v0.28.0
cargo run --release -- tests/svg/a-path-001.svg tests/png/a-path-001.png
```

There will be an error:

```
thread 'main' panicked at 'the previous segment must be M/L/C', usvg/src/pathdata.rs:219:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

image

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Very strange. If I downgrade just `kurbo` - it still works just fine. Will investigate.

**Comment by RazrFalcon** [comment]
See: https://github.com/RazrFalcon/resvg/tree/master/tests#adding-a-new-test

The PNG should be 300x300. And call it `e-path-053.svg`

**Comment by yisibl** [comment]
I also tried to downgrade kurbo, and it did.

**Comment by RazrFalcon** [comment]
Can confirm on v0.28. Very strange. Will have to investigate the cause.

**Comment by yisibl** [comment]
Since our online service relies on new releases, I have prioritized the release of `resvg-js` 2.4.0. I will update ChangeLog as soon as you have new findings.

https://github.com/yisibl/resvg-js/releases/tag/v2.4.0

**Comment by RazrFalcon** [comment]
Finally found to look into it and it's bizarre. I worked with SVG for more than 10 year and I didn't knew that MoveTo after ClosePath is optional...

>If a "closepath" is followed immediately by any other command, then the next subpath starts at the same initial point as the current subpath.

Meaning that `M L z A` is totally fine. And `resvg` doesn't handle this case properly. It got accidentally fixed, but there is still a bug.

**Comment by RazrFalcon** [comment]
Yes, this was an SVG path data parsing bug. Not even `usvg` one. Somehow the bug slipped unnoticed. Now it's fine.

**Pull request merged**
