### PR TITLE
fix blur issue

### PR DESCRIPTION
**Pull request by m1guelpf**
@yisibl's fix for #241

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Looks like it breaks the current output quite a bit. Will take a look.

**Comment by RazrFalcon** [comment]
Doesn't seem to work at all. Try rendering `tests/svg/e-filter-002.svg`. It's has no blur anymore.

**Comment by yisibl** [comment]
Yes, this PR will introduce new problems. We desperately need a better program.

**Comment by m1guelpf** [comment]
hmm, I'm using [this fork](https://github.com/zimond/resvg/tree/resvg-31)(which includes the commit above, along with a bunch of other changes), and it fixes the issue for [my use-case](https://github.com/m1guelpf/world-id-marbles/blob/5ce76318814a1f2f96723149bbecc47e77e89e4d/packages/world-id-marbles/src/lib.rs#L126-L144).

**Comment by RazrFalcon** [comment]
Well, in it's current form it break most resvg tests. I cannot accept it.

**Pull request closed without merging**
