### PR TITLE
Update to raqote 0.7.3

### PR DESCRIPTION
**Pull request by jrmuizel**
This update makes a significant improvement in the micro benchmark numbers.

### CODE REVIEW

**Comment by jrmuizel** [comment]
Looks like I broke something. Trying again with suggest the upgrade not the performance improvements.

**Comment by jrmuizel** [comment]
Looks like even that is broken...

**Comment by RazrFalcon** [comment]
Yeap.

`a-shape-rendering-002.svg`:

```
/home/razr/.cargo/bin/cargo run --color=always --features raqote-backend -- --dump-svg dump.svg --backend raqote test.svg out.png
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/rendersvg --dump-svg dump.svg --backend raqote test.svg out.png`
thread 'main' panicked at 'index out of bounds: the len is 25601 but the index is 25648', /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/slice/mod.rs:2721:14
stack backtrace:
   0:     0x565555a8a57b - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x565555a8a57b - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x565555a8a57b - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x565555a8a57b - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x565555a8a57b - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x565555a8a256 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x565555a8aced - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x565555a8a872 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x565555a8a756 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x565555aa9dcd - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x565555aa9d85 - core::panicking::panic_bounds_check::hf0c95c4cc84d34ca
                               at src/libcore/panicking.rs:61
  11:     0x565555a6041d - <usize as core::slice::SliceIndex<[T]>>::index_mut::h9f549a6e62434701
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/slice/mod.rs:2721
  12:     0x565555a5fff8 - core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut::h7d1ba5ef0cdd6bf1
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/slice/mod.rs:2576
  13:     0x565555a5a6eb - <alloc::vec::Vec<T> as core::ops::index::IndexMut<I>>::index_mut::h4a690db4a768e53c
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/vec.rs:1803
  14:     0x5655559c09e6 - <raqote::blitter::MaskBlitter as raqote::blitter::RasterBlitter>::blit_span::h8346528fe634fef3
                               at /home/razr/.cargo/registry/src/github.com-1ecc6299db9ec823/raqote-0.7.1/src/blitter.rs:124
  15:     0x5655559e2c4d - raqote::rasterizer::Rasterizer::scan_edges::h613839e38e8b54fe
                               at /home/razr/.cargo/registry/src/github.com-1ecc6299db9ec823/raqote-0.7.1/src/rasterizer.rs:487
  16:     0x5655559e2f73 - raqote::rasterizer::Rasterizer::rasterize::h341b4a5342f39dab
                               at /home/razr/.cargo/registry/src/github.com-1ecc6299db9ec823/raqote-0.7.1/src/rasterizer.rs:559
  17:     0x5655559bd91a - raqote::draw_target::DrawTarget::fill::hb9da14d3f18e7484
                               at /home/razr/.cargo/registry/src/github.com-1ecc6299db9ec823/raqote-0.7.1/src/draw_target.rs:568
  18:     0x5655556c918f - resvg::backend_raqote::style::fill::h1bcfaeb47c224365
                               at src/backend_raqote/style.rs:52
  19:     0x5655556b4b1d - resvg::backend_raqote::path::draw::h09395ba47670fa26
                               at src/backend_raqote/path.rs:45
  20:     0x56555565b4ca - resvg::backend_raqote::render_node::hbe9f9dbe7e98bff9
                               at src/backend_raqote/mod.rs:242
  21:     0x56555565b8b1 - resvg::backend_raqote::render_group::hd79b3f07dd2bf630
                               at src/backend_raqote/mod.rs:279
  22:     0x56555565b427 - resvg::backend_raqote::render_node::hbe9f9dbe7e98bff9
                               at src/backend_raqote/mod.rs:239
  23:     0x56555565b07c - resvg::backend_raqote::render_node_to_canvas_impl::h904990600c273864
                               at src/backend_raqote/mod.rs:205
  24:     0x56555565aeb8 - resvg::backend_raqote::render_node_to_canvas::h2f6cd5e812867dfc
                               at src/backend_raqote/mod.rs:185
  25:     0x56555565aded - resvg::backend_raqote::render_to_canvas::h9ae989fda4ddcc4d
                               at src/backend_raqote/mod.rs:174
  26:     0x56555565a5d1 - resvg::backend_raqote::render_to_image::h460a37a2471ab2c9
                               at src/backend_raqote/mod.rs:133
  27:     0x565555659d96 - <resvg::backend_raqote::Backend as resvg::Render>::render_to_image::ha9cf25295836e164
                               at src/backend_raqote/mod.rs:97
  28:     0x5655555ebe7c - rendersvg::process::{{closure}}::h52e5686ee7887dfe
                               at tools/rendersvg/src/main.rs:105
  29:     0x5655555ec396 - rendersvg::run_task::hc3d681cc315ada55
                               at tools/rendersvg/src/main.rs:160
  30:     0x5655555e0255 - rendersvg::process::hc7e1c9156db1ad7a
                               at tools/rendersvg/src/main.rs:105
  31:     0x5655555df6c1 - rendersvg::main::hf6750731f6ccf17f
                               at tools/rendersvg/src/main.rs:26
  32:     0x5655555eb7d0 - std::rt::lang_start::{{closure}}::h1d1bb82aefd221ce
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  33:     0x565555a8a6f3 - std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955
                               at src/libstd/rt.rs:49
  34:     0x565555a8a6f3 - std::panicking::try::do_call::h9440ccd4dc467eaa
                               at src/libstd/panicking.rs:296
  35:     0x565555a91c5a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  36:     0x565555a8b1fd - std::panicking::try::hc046e7ee42ee744f
                               at src/libstd/panicking.rs:275
  37:     0x565555a8b1fd - std::panic::catch_unwind::h27dfc457c200aee0
                               at src/libstd/panic.rs:394
  38:     0x565555a8b1fd - std::rt::lang_start_internal::hea1b49a567afe309
                               at src/libstd/rt.rs:48
  39:     0x5655555eb7a9 - std::rt::lang_start::h221e2b90041033c1
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  40:     0x5655555e1ada - main
  41:     0x7efbff3b4e5b - __libc_start_main
  42:     0x5655555d719a - _start
  43:                0x0 - <unknown>
```

**Comment by RazrFalcon** [comment]
I've added more detailed error messages and rerun the CI.

**Comment by RazrFalcon** [comment]
I've benched this patch and there are indeed some improvements.

- `nested_clip_path_raqote` is 37% faster
- `clip_path_raqote` is 29% faster
- `mask_raqote` is 10% faster
-  `blend_multiply_raqote` is 18% faster

**Comment by jrmuizel** [comment]
I haven't checked all of the failures but the ones I looked at seemed like they were small pixel differences that shouldn't block merging.

**Comment by RazrFalcon** [comment]
Yes, it's a rounding issue. Green 0,128,0 became 0,127,0.

Can you add:

```
a-opacity-003.svg
a-overflow-001.svg
a-overflow-003.svg
e-marker-022.svg
e-mask-013.svg
e-mask-014.svg
e-mask-022.svg
e-mask-027.svg
```

to the `./testing-tools/regression/allow-raqote.txt`

**Comment by jrmuizel** [comment]
I needed to re-add `a-enable-background-016.svg` `a-enable-background-017.svg` as well.

**Comment by RazrFalcon** [comment]
Thanks!

**Comment by jrmuizel** [comment]
Can you rerun the benchmarks on top of this?

**Comment by RazrFalcon** [comment]
Done.

**Pull request merged**
