### PR TITLE
Add support for decoding WebP images

### PR DESCRIPTION
**Pull request by notjosh**
Hiya 👋 

I was hoping to use WebP in a project, and noticed (via #575) that the `image-webp` project has been published now. This PR adds support for the project within `resvg`.

As noted in #575 there _may_ be performance issues - I haven't tested extensively. However in my use case, it saves a step of converting `.webp` images to a compatible format, so even a slow(ish) implementation is an overall positive. With that in mind, it feels like a step forward for `resvg` to support WebP, even if there's still room in future for their (pre-1.0) project to improve.

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Looks good to me. All we have to do now is to ask them nicely to stop using `thiserror`.

**Comment by RazrFalcon** [comment]
https://github.com/image-rs/image-webp/issues/66

**Comment by RazrFalcon** [comment]
Looks like we need a MSRV bump as well.

**Comment by RazrFalcon** [comment]
Ok, waiting for 0.1.3 and I'm ready to merge.

**Comment by adamJLev** [comment]
any updates on this? would be great to have webp support ❤️

**Comment by LaurenzV** [comment]
Still waiting for the new release I think.

**Comment by notjosh** [comment]
[0.1.3](https://github.com/image-rs/image-webp/releases/tag/v0.1.3) was just released, so I'll rebase & clean up the PR soon....ish. I've got some family in town so it might be a couple of days.

**Comment by RazrFalcon** [comment]
Sure, no problem.

**Comment by notjosh** [comment]
Okie doke, tests are green locally, so this should now be ready to review.

**Comment by notjosh** [comment]
> error: package `image-webp v0.1.3` cannot be built because it requires rustc 1.67.1 or newer, while the currently active rustc version is 1.65.0

How much of a dealbreaker is this? And/or as `image-webp` is an optional dependency, anyone that doesn't want to opt into the feature can continue to use `< 1.67.1` version, I guess?

**Comment by RazrFalcon** [comment]
We can bump MSRV no problem. It's set in:
- `.github/workflows/main.yml`
- `README.md`

**Comment by notjosh** [comment]
@RazrFalcon bumped MSRV, can you approve workflow? tyty.

Also, do you want me to bump `CHANGELOG.md` within the PR, or do you author those (for consistency etc)?

**Comment by RazrFalcon** [comment]
All good, thanks.

**Pull request merged**
