### PR TITLE
Fix text path placement bug

### PR DESCRIPTION
**Pull request by chubei-oppen**

### CODE REVIEW

**Comment by chubei-oppen** [comment]
@RazrFalcon I think this is ready for review. Do we need to add test cases?

**Comment by RazrFalcon** [comment]
Yes, please add a minimal reproducible test. It should be named `e-textPath-038.svg` (just in case).

**Comment by chubei-oppen** [comment]
Sorry, what does 038 in the file name mean?

**Comment by RazrFalcon** [comment]
Just a serial number. See: https://github.com/RazrFalcon/resvg/blob/master/tests/README.md

**Comment by chubei-oppen** [comment]
Oh I didn't notice these tests. Was playing around in the usvg crate. Actually this pull request breaks almost all the text path tests because the characters' positions are changed. Do I update them all?

**Comment by RazrFalcon** [comment]
Yes. I've updated the instruction, so it explains how to generate PNG's now.

Also, can you reset the Cargo.lock. Looks like you've updated all dependencies, not only kurbo.

**Comment by chubei-oppen** [comment]
Thanks. I didn’t fully understand how Cargo works and accidentally updated .lock during testing. Will reset it.

I think a new test isn’t necessary because current textPath tests already provide a good coverage to possible cases?

**Comment by RazrFalcon** [comment]
I think so. I would be great if you can write a test that clearly shows the issue, but this is not a requirement. I maybe do this myself later.

**Comment by chubei-oppen** [comment]
@RazrFalcon My build fails about a quater of the tests with code on master.

The images look the same from human eyes, but pixel values differ.

I'm using Linux 5.4.0-52-generic, 18.04.1-Ubuntu, clang version 6.0.0-1ubuntu2, cargo 1.47.0.
<details>
<summary>Tests output is here</summary>

running 1 test
test render ... FAILED

failures:

---- render stdout ----
a-baseline-shift-015 is different by 11 pixels
a-baseline-shift-016 is different by 11 pixels
a-baseline-shift-017 is different by 11 pixels
a-baseline-shift-018 is different by 11 pixels
a-baseline-shift-020 is different by 2 pixels
a-baseline-shift-021 is different by 2 pixels
a-enable-background-012 is different by 69 pixels
a-enable-background-017 is different by 5625 pixels
a-enable-background-018 is different by 120 pixels
a-fill-opacity-006 is different by 5 pixels
a-fill-rule-001 is different by 291 pixels
a-fill-rule-002 is different by 226 pixels
a-font-size-005 is different by 5 pixels
a-image-rendering-002 is different by 27 pixels
a-marker-end-001 is different by 203 pixels
a-marker-mid-001 is different by 215 pixels
a-marker-start-001 is different by 199 pixels
a-opacity-001 is different by 191 pixels
a-overflow-001 is different by 238 pixels
a-overflow-002 is different by 199 pixels
a-overflow-003 is different by 238 pixels
a-shape-rendering-001 is different by 168 pixels
a-shape-rendering-004 is different by 168 pixels
a-stroke-016 is different by 91 pixels
a-stroke-017 is different by 44 pixels
a-stroke-018 is different by 415 pixels
a-stroke-019 is different by 245 pixels
a-stroke-dasharray-012 is different by 59 pixels
a-stroke-linecap-001 is different by 354 pixels
a-stroke-linecap-002 is different by 363 pixels
a-stroke-linecap-003 is different by 398 pixels
a-stroke-linecap-004 is different by 16 pixels
a-stroke-linecap-007 is different by 286 pixels
a-stroke-linecap-008 is different by 329 pixels
a-stroke-linecap-009 is different by 309 pixels
a-stroke-linejoin-002 is different by 1 pixels
a-stroke-miterlimit-001 is different by 8 pixels
a-stroke-miterlimit-002 is different by 8 pixels
a-stroke-miterlimit-003 is different by 8 pixels
a-stroke-miterlimit-004 is different by 8 pixels
a-stroke-miterlimit-005 is different by 8 pixels
a-text-anchor-008 is different by 128 pixels
a-text-anchor-009 is different by 2 pixels
a-text-anchor-010 is different by 38 pixels
a-text-decoration-008 is different by 502 pixels
a-text-decoration-009 is different by 1 pixels
a-text-decoration-010 is different by 1 pixels
a-text-decoration-011 is different by 14 pixels
a-text-decoration-013 is different by 33 pixels
a-transform-001 is different by 223 pixels
a-transform-006 is different by 504 pixels
a-transform-007 is different by 253 pixels
a-transform-013 is different by 223 pixels
a-transform-014 is different by 223 pixels
a-visibility-007 is different by 1 pixels
a-word-spacing-002 is different by 1 pixels
a-word-spacing-005 is different by 1 pixels
a-writing-mode-014 is different by 2 pixels
a-writing-mode-017 is different by 9 pixels
e-circle-001 is different by 218 pixels
e-circle-002 is different by 168 pixels
e-circle-003 is different by 50 pixels
e-circle-004 is different by 112 pixels
e-circle-005 is different by 31 pixels
e-circle-006 is different by 168 pixels
e-clipPath-007 is different by 7 pixels
e-clipPath-019 is different by 5 pixels
e-clipPath-020 is different by 8 pixels
e-clipPath-021 is different by 9 pixels
e-clipPath-029 is different by 5 pixels
e-clipPath-031 is different by 2 pixels
e-clipPath-034 is different by 7 pixels
e-clipPath-036 is different by 8 pixels
e-clipPath-037 is different by 9 pixels
e-ellipse-001 is different by 208 pixels
e-ellipse-005 is different by 65 pixels
e-ellipse-006 is different by 97 pixels
e-ellipse-007 is different by 32 pixels
e-feComponentTransfer-020 is different by 25344 pixels
e-feConvolveMatrix-001 is different by 3535 pixels
e-feConvolveMatrix-002 is different by 3535 pixels
e-feConvolveMatrix-003 is different by 3224 pixels
e-feConvolveMatrix-007 is different by 3616 pixels
e-feConvolveMatrix-012 is different by 544 pixels
e-feConvolveMatrix-016 is different by 3600 pixels
e-feConvolveMatrix-019 is different by 3616 pixels
e-feConvolveMatrix-020 is different by 3616 pixels
e-feConvolveMatrix-022 is different by 3152 pixels
e-feConvolveMatrix-024 is different by 2580 pixels
e-feConvolveMatrix-025 is different by 3120 pixels
e-feFlood-004 is different by 50544 pixels
e-feGaussianBlur-012 is different by 769 pixels
e-feImage-019 is different by 2 pixels
e-feMerge-003 is different by 23 pixels
e-feMorphology-013 is different by 3600 pixels
e-feOffset-008 is different by 178 pixels
e-filter-026 is different by 510 pixels
e-filter-027 is different by 249 pixels
e-filter-052 is different by 628 pixels
e-filter-053 is different by 37390 pixels
e-filter-054 is different by 16271 pixels
e-filter-058 is different by 256 pixels
e-image-003 is different by 27 pixels
e-image-006 is different by 27 pixels
e-image-007 is different by 27 pixels
e-image-008 is different by 27 pixels
e-image-017 is different by 1 pixels
e-image-018 is different by 7 pixels
e-image-019 is different by 3 pixels
e-image-021 is different by 2 pixels
e-image-022 is different by 1 pixels
e-image-024 is different by 1 pixels
e-image-039 is different by 27 pixels
e-line-003 is different by 172 pixels
e-line-004 is different by 293 pixels
e-line-005 is different by 43 pixels
e-line-006 is different by 107 pixels
e-line-007 is different by 142 pixels
e-line-008 is different by 142 pixels
e-line-009 is different by 236 pixels
e-marker-001 is different by 187 pixels
e-marker-002 is different by 163 pixels
e-marker-003 is different by 163 pixels
e-marker-004 is different by 163 pixels
e-marker-005 is different by 199 pixels
e-marker-006 is different by 215 pixels
e-marker-007 is different by 203 pixels
e-marker-008 is different by 203 pixels
e-marker-009 is different by 199 pixels
e-marker-010 is different by 197 pixels
e-marker-011 is different by 223 pixels
e-marker-012 is different by 3 pixels
e-marker-013 is different by 338 pixels
e-marker-014 is different by 14 pixels
e-marker-015 is different by 321 pixels
e-marker-018 is different by 203 pixels
e-marker-019 is different by 2085 pixels
e-marker-020 is different by 197 pixels
e-marker-021 is different by 197 pixels
e-marker-022 is different by 373 pixels
e-marker-023 is different by 223 pixels
e-marker-024 is different by 223 pixels
e-marker-025 is different by 223 pixels
e-marker-026 is different by 223 pixels
e-marker-027 is different by 223 pixels
e-marker-028 is different by 197 pixels
e-marker-029 is different by 197 pixels
e-marker-030 is different by 197 pixels
e-marker-031 is different by 1242 pixels
e-marker-032 is different by 1242 pixels
e-marker-033 is different by 48 pixels
e-marker-034 is different by 30 pixels
e-marker-035 is different by 98 pixels
e-marker-036 is different by 163 pixels
e-marker-037 is different by 231 pixels
e-marker-038 is different by 230 pixels
e-marker-039 is different by 206 pixels
e-marker-040 is different by 211 pixels
e-marker-041 is different by 215 pixels
e-marker-043 is different by 300 pixels
e-marker-044 is different by 311 pixels
e-marker-045 is different by 1 pixels
e-marker-046 is different by 219 pixels
e-marker-047 is different by 214 pixels
e-marker-048 is different by 152 pixels
e-marker-049 is different by 364 pixels
e-marker-050 is different by 175 pixels
e-marker-051 is different by 161 pixels
e-marker-052 is different by 157 pixels
e-marker-053 is different by 228 pixels
e-marker-054 is different by 260 pixels
e-marker-055 is different by 28 pixels
e-marker-056 is different by 28 pixels
e-marker-057 is different by 223 pixels
e-marker-058 is different by 217 pixels
e-mask-012 is different by 41280 pixels
e-mask-013 is different by 19680 pixels
e-mask-014 is different by 36960 pixels
e-mask-015 is different by 28 pixels
e-mask-022 is different by 19320 pixels
e-mask-028 is different by 106 pixels
e-path-003 is different by 356 pixels
e-path-006 is different by 88 pixels
e-path-007 is different by 109 pixels
e-path-008 is different by 112 pixels
e-path-009 is different by 199 pixels
e-path-010 is different by 105 pixels
e-path-012 is different by 439 pixels
e-path-013 is different by 77 pixels
e-path-014 is different by 135 pixels
e-path-015 is different by 220 pixels
e-path-021 is different by 252 pixels
e-path-022 is different by 252 pixels
e-path-026 is different by 335 pixels
e-path-027 is different by 280 pixels
e-path-028 is different by 328 pixels
e-path-029 is different by 152 pixels
e-path-030 is different by 152 pixels
e-path-031 is different by 538 pixels
e-path-032 is different by 59 pixels
e-path-033 is different by 55 pixels
e-path-034 is different by 29 pixels
e-path-035 is different by 31 pixels
e-path-036 is different by 59 pixels
e-path-037 is different by 30 pixels
e-path-038 is different by 27 pixels
e-path-039 is different by 30 pixels
e-path-040 is different by 418 pixels
e-path-041 is different by 418 pixels
e-path-042 is different by 244 pixels
e-path-043 is different by 244 pixels
e-path-044 is different by 140 pixels
e-path-045 is different by 272 pixels
e-path-046 is different by 211 pixels
e-path-047 is different by 124 pixels
e-path-048 is different by 72 pixels
e-path-049 is different by 116 pixels
e-path-050 is different by 188 pixels
e-path-051 is different by 203 pixels
e-pattern-001 is different by 179 pixels
e-pattern-002 is different by 198 pixels
e-pattern-003 is different by 179 pixels
e-pattern-004 is different by 173 pixels
e-pattern-005 is different by 625 pixels
e-pattern-006 is different by 84 pixels
e-pattern-007 is different by 8 pixels
e-pattern-008 is different by 8 pixels
e-pattern-009 is different by 229 pixels
e-pattern-010 is different by 8 pixels
e-pattern-011 is different by 217 pixels
e-pattern-012 is different by 244 pixels
e-pattern-013 is different by 244 pixels
e-pattern-014 is different by 167 pixels
e-pattern-015 is different by 167 pixels
e-pattern-016 is different by 167 pixels
e-pattern-017 is different by 244 pixels
e-pattern-018 is different by 242 pixels
e-pattern-019 is different by 8 pixels
e-pattern-020 is different by 8 pixels
e-pattern-021 is different by 8 pixels
e-pattern-022 is different by 229 pixels
e-pattern-023 is different by 229 pixels
e-pattern-024 is different by 191 pixels
e-pattern-025 is different by 8 pixels
e-pattern-026 is different by 175 pixels
e-pattern-027 is different by 191 pixels
e-pattern-028 is different by 179 pixels
e-pattern-029 is different by 217 pixels
e-polygon-001 is different by 57 pixels
e-polygon-003 is different by 178 pixels
e-polygon-004 is different by 178 pixels
e-polyline-001 is different by 195 pixels
e-polyline-003 is different by 195 pixels
e-polyline-004 is different by 195 pixels
e-rect-004 is different by 49 pixels
e-rect-005 is different by 43 pixels
e-rect-006 is different by 43 pixels
e-rect-013 is different by 43 pixels
e-rect-014 is different by 43 pixels
e-rect-018 is different by 220 pixels
e-rect-019 is different by 220 pixels
e-rect-020 is different by 115 pixels
e-rect-021 is different by 85 pixels
e-rect-022 is different by 60 pixels
e-rect-023 is different by 60 pixels
e-rect-024 is different by 37 pixels
e-svg-022 is different by 168 pixels
e-svg-023 is different by 168 pixels
e-svg-025 is different by 37 pixels
e-svg-026 is different by 22 pixels
e-svg-027 is different by 27 pixels
e-svg-028 is different by 1 pixels
e-svg-029 is different by 1 pixels
e-text-010 is different by 2 pixels
e-text-018 is different by 7 pixels
e-text-020 is different by 15 pixels
e-text-021 is different by 3 pixels
e-text-024 is different by 1 pixels
e-text-026 is different by 3 pixels
e-text-027 is different by 1 pixels
e-text-030 is different by 1 pixels
e-text-033 is different by 2 pixels
e-textPath-001 is different by 143 pixels
e-textPath-002 is different by 143 pixels
e-textPath-003 is different by 156 pixels
e-textPath-004 is different by 153 pixels
e-textPath-005 is different by 147 pixels
e-textPath-006 is different by 153 pixels
e-textPath-007 is different by 143 pixels
e-textPath-008 is different by 143 pixels
e-textPath-009 is different by 190 pixels
e-textPath-010 is different by 190 pixels
e-textPath-011 is different by 143 pixels
e-textPath-012 is different by 54 pixels
e-textPath-013 is different by 179 pixels
e-textPath-014 is different by 183 pixels
e-textPath-015 is different by 68 pixels
e-textPath-017 is different by 153 pixels
e-textPath-019 is different by 152 pixels
e-textPath-020 is different by 213 pixels
e-textPath-021 is different by 146 pixels
e-textPath-022 is different by 140 pixels
e-textPath-023 is different by 152 pixels
e-textPath-024 is different by 295 pixels
e-textPath-026 is different by 20 pixels
e-textPath-028 is different by 143 pixels
e-textPath-029 is different by 149 pixels
e-textPath-030 is different by 207 pixels
e-textPath-031 is different by 141 pixels
e-textPath-033 is different by 1 pixels
e-textPath-034 is different by 100 pixels
e-textPath-035 is different by 183 pixels
e-textPath-036 is different by 75 pixels
e-textPath-037 is different by 81 pixels
e-tref-001 is different by 7 pixels
e-tref-002 is different by 30 pixels
e-tref-004 is different by 1 pixels
e-tref-006 is different by 7 pixels
e-tref-007 is different by 7 pixels
e-tref-008 is different by 19 pixels
e-tref-011 is different by 7 pixels
e-tspan-009 is different by 20 pixels
e-tspan-010 is different by 17 pixels
e-tspan-016 is different by 370 pixels
e-tspan-023 is different by 1 pixels
e-tspan-026 is different by 2 pixels
e-tspan-027 is different by 2 pixels
e-tspan-028 is different by 7 pixels
e-tspan-029 is different by 4 pixels
thread 'render' panicked at 'failed', tests/render.rs:62:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    render

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

</details>


Do you have any idea what might have happend?

**Comment by RazrFalcon** [comment]
Hmm... Yes, it's a known Skia bug. On some hardware it produces different results. I suggest waiting for tiny-skia 0.2, and then applying this patch. I hope it would happen this weekends.

**Comment by chubei-oppen** [comment]
Great. Thank you for your incredible work.

**Comment by RazrFalcon** [comment]
It should be fine now.

**Comment by chubei-oppen** [comment]
Works like a charm. I've updated the test images.

**Comment by RazrFalcon** [comment]
Thank!

**Pull request merged**
