### PR TITLE
Update to new version of fontdb

### PR DESCRIPTION
**Pull request by tronical**

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Sorry, but I do not accept dependency bump patches. And I had no plans in updating resvg anytime soon. Do you need a new resvg release with the new fontdb?

**Comment by tronical** [comment]
>  Do you need a new resvg release with the new fontdb?

Yes :)

**Comment by RazrFalcon** [comment]
Ok, I will make one soon.

**Comment by tronical** [comment]
Thank you!

**Pull request closed without merging**
